config/routes.rb
Rails.application.routes.draw do
  get 'mean/index'
  post 'mean/reset'
  post 'mean/update'
  root 'mean#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mean_controller.rb
class MeanController < ApplicationController
  def index
    numbers_looked_at = session[:numbers_looked_at]
    numbers_looked_at ||= 0
    if numbers_looked_at > 0
      @mean = session[:mean]
    else
      @mean = 0
    end
  end

  def update
    if invalid_number?
      flash[:notice] = "Please enter a valid number"
      redirect_to mean_index_path
      return
    end

    number = params[:number].to_i

    numbers_looked_at = session[:numbers_looked_at]
    numbers_looked_at ||= 0


    if numbers_looked_at == 0
      new_mean = number
    else
      cur_mean = session[:mean]
      cur_sum = cur_mean * numbers_looked_at
      new_sum = cur_sum + number
      new_mean = new_sum / (numbers_looked_at + 1)
    end
    session[:mean] = new_mean
    session[:numbers_looked_at] = (numbers_looked_at + 1)
    redirect_to mean_index_path
  end

  def reset
    session[:mean] = 0
    session[:numbers_looked_at] = 0
    redirect_to mean_index_path
  end

  private
  def invalid_number?
    valid_number = params[:number] && (params[:number] =~ /\d+/)
    not valid_number
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mean_helper.rb
module MeanHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/mean/index.html.erb
<%= form_tag(mean_update_path, :id => "update_form") do %>
  <%= label_tag(:number, "Enter Number:") %>
  <%= text_field_tag(:number) %>
  <%= submit_tag("Calculate Mean") %>
<% end %>
<p>
Mean is: <span id="mean"><%= @mean %> </span>.
</p>
<p>
<%= form_tag(mean_reset_path, :id => "reset_form") do %>
  <%= submit_tag("Reset form") %>
<% end %>
</p>

app/views/mean/update.html.erb
<h1>Mean#update</h1>
<p>Find me in app/views/mean/update.html.erb</p>